{% set name = "dist-s1" %}
{% set version = "2.0.17" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2d/df/8b64dbc275cea6f0c87f4fbd129a4c1d7ac82cfaaf61b91c5c40506d08bb/dist_s1-{{ version }}.tar.gz
  sha256: 5cb5f27395340ce620bf353a39dd14c69da647f5f7a59fe7484f51b02a013337

build:
  entry_points:
    - dist-s1 = dist_s1.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - asf_search
    - backoff
    - click
    - dem_stitcher
    - dist_s1_enumerator
    - distmetrics >=0.0.10
    - geopandas
    - numpy
    - pandas
    - pydantic
    - tile_mate >=0.0.12
    - pyyaml
    - rasterio >=1.4.0
    - ruff
    - scipy

test:
  imports:
    - dist_s1
  commands:
    - pip check
    - dist-s1 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opera-adt/dist-s1
  summary: The workflow to generate the DIST-S1 product
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
